export const products = [
    {
        id: "1",
        title: "Digital Marketing Masterclass (2022 Edition)",
        description: "This is a digital marketing masterclass that will help you learn how to market your business online. You will learn how to create a digital marketing strategy, how to create a digital marketing plan, and how to create a digital marketing campaign.",
        price: 99.00,
        discount: 20,
        image: "/products-banner/01.jpg",
        lecturer: "Frances Guerreror",
        lecturerImage: "/profile-2.png",
        category: "Digital Marketing",
        level: "Beginner",
        students: 190,
        rating: 4.9,
        durations: "9h 30m",
        lectures: 82,
    },
    {
        id: "2",
        title: "Digital Marketing Masterclass (2022 Edition)",
        description: "This is a digital marketing masterclass that will help you learn how to market your business online. You will learn how to create a digital marketing strategy, how to create a digital marketing plan, and how to create a digital marketing campaign.",
        price: 99.00,
        discount: 20,
        image: "/products-banner/02.jpg",
        lecturer: "Frances Guerreror",
        lecturerImage: "/profile-2.png",
        category: "Digital Marketing",
        level: "Beginner",
        students: 190,
        rating: 4.9,
        durations: "9h 30m",
        lectures: 82,
    },
    {
        id: "3",
        title: "Digital Marketing Masterclass (2022 Edition)",
        description: "This is a digital marketing masterclass that will help you learn how to market your business online. You will learn how to create a digital marketing strategy, how to create a digital marketing plan, and how to create a digital marketing campaign.",
        price: 99.00,
        discount: 20,
        image: "/products-banner/03.jpg",
        lecturer: "Frances Guerreror",
        lecturerImage: "/profile-2.png",
        category: "Digital Marketing",
        level: "Beginner",
        students: 190,
        rating: 4.9,
        durations: "9h 30m",
        lectures: 82,
    },
    {
        id: "4",
        title: "Digital Marketing Masterclass (2022 Edition)",
        description: "This is a digital marketing masterclass that will help you learn how to market your business online. You will learn how to create a digital marketing strategy, how to create a digital marketing plan, and how to create a digital marketing campaign.",
        price: 99.00,
        discount: 20,
        image: "/products-banner/04.jpg",
        lecturer: "Frances Guerreror",
        lecturerImage: "/profile-2.png",
        category: "Digital Marketing",
        level: "Beginner",
        students: 190,
        rating: 4.9,
        durations: "9h 30m",
        lectures: 82,
    },
    {
        id: "5",
        title: "Digital Marketing Masterclass (2022 Edition)",
        description: "This is a digital marketing masterclass that will help you learn how to market your business online. You will learn how to create a digital marketing strategy, how to create a digital marketing plan, and how to create a digital marketing campaign.",
        price: 99.00,
        discount: 20,
        image: "/products-banner/05.jpg",
        lecturer: "Frances Guerreror",
        lecturerImage: "/profile-2.png",
        category: "Digital Marketing",
        level: "Beginner",
        students: 190,
        rating: 4.9,
        durations: "9h 30m",
        lectures: 82,
    },
    {
        id: "6",
        title: "Digital Marketing Masterclass (2022 Edition)",
        description: "This is a digital marketing masterclass that will help you learn how to market your business online. You will learn how to create a digital marketing strategy, how to create a digital marketing plan, and how to create a digital marketing campaign.",
        price: 99.00,
        discount: 20,
        image: "/products-banner/06.jpg",
        lecturer: "Frances Guerreror",
        lecturerImage: "/profile-2.png",
        category: "Digital Marketing",
        level: "Beginner",
        students: 190,
        rating: 4.9,
        durations: "9h 30m",
        lectures: 82,
    }
]